
# Listen on these ports.
listen: :8888

# Define our backends. These will be used to handle the proxied
# requests for routes they match.
backends:
  -
    name: django
    host: http://localhost:8000
  -
    name: node
    host: http://localhost:5000
  -
    name: rails
    host: http://localhost:3000

# Define our routes, processed in this order. The first route
# to match a request is used.
routes:
  -
    path: /hpa/**
    route: http://localhost:8000/hpa/
  -
    path: /jobs
    route: django
  -
    path: /jobs/**
    route: django
  -
    path: /auth/**
    route: django
  # If we haven't matched anything yet, everything else goes to
  # the default route, which matches all requests
  -
    path: /**
    route: rails
